// Static templates and fallback data for Hyrinx Rental
export interface WebsiteTemplate {
  id: string
  name: string
  slug: string
  category: string
  description: string
  shortDesc: string
  featured: boolean
  published: boolean
  startingPrice: number
  thumbnail?: string
  liveDemoUrl?: string
  features: string[]
  customization: string[]
}

export const DEFAULT_PRICING_PLANS = [
  { id: 'plan-1-day', name: '1 Day', duration: '1 Day', durationDays: 1, price: 149, description: 'Perfect for quick celebrations', popular: false, active: true },
  { id: 'plan-3-days', name: '3 Days', duration: '3 Days', durationDays: 3, price: 399, description: 'Short events & surprises', popular: false, active: true },
  { id: 'plan-7-days', name: '7 Days', duration: '7 Days', durationDays: 7, price: 599, description: 'Most popular', popular: true, active: true },
  { id: 'plan-15-days', name: '15 Days', duration: '15 Days', durationDays: 15, price: 799, description: 'Events & campaigns', popular: false, active: true },
  { id: 'plan-1-month', name: '1 Month', duration: '1 Month', durationDays: 30, price: 1099, description: 'Startups & projects', popular: false, active: true },
  { id: 'plan-3-months', name: '3 Months', duration: '3 Months', durationDays: 90, price: 2099, description: 'Growing businesses', popular: false, active: true },
  { id: 'plan-6-months', name: '6 Months', duration: '6 Months', durationDays: 180, price: 3599, description: 'Longer use & branding', popular: false, active: true },
  { id: 'plan-1-year', name: '1 Year', duration: '1 Year', durationDays: 365, price: 6099, description: 'Complete online presence', popular: false, active: true },
]

export const DEFAULT_CATEGORIES = [
  { id: 'cat-wedding', name: 'Wedding', slug: 'wedding', enabled: true },
  { id: 'cat-birthday', name: 'Birthday', slug: 'birthday', enabled: true },
  { id: 'cat-invitation', name: 'Invitation', slug: 'invitation', enabled: true },
  { id: 'cat-college', name: 'College', slug: 'college', enabled: true },
  { id: 'cat-business', name: 'Business', slug: 'business', enabled: true },
  { id: 'cat-portfolio', name: 'Portfolio', slug: 'portfolio', enabled: true },
  { id: 'cat-startup', name: 'Startup', slug: 'startup', enabled: true },
  { id: 'cat-product-launch', name: 'Product Launch', slug: 'product-launch', enabled: true },
  { id: 'cat-events', name: 'Events', slug: 'events', enabled: true },
  { id: 'cat-project', name: 'Project', slug: 'project', enabled: true },
  { id: 'cat-celebration', name: 'Celebration', slug: 'celebration', enabled: true },
  { id: 'cat-personal', name: 'Personal', slug: 'personal', enabled: true },
]

export const DEFAULT_WEBSITES: WebsiteTemplate[] = [
  // Wedding
  {
    id: 'web-eternal-moments',
    name: 'Eternal Moments',
    slug: 'eternal-moments',
    category: 'Wedding',
    description: 'Elegant luxury wedding website featuring couple love story, ceremony itinerary, RSVP form, and interactive location map.',
    shortDesc: 'Luxury wedding celebration website with story, venue details, and RSVP.',
    featured: true,
    published: true,
    startingPrice: 149,
    features: ['Love Story Timeline', 'Digital RSVP', 'Venue Directions', 'Event Schedule', 'Photo Gallery'],
    customization: ['Couple Names', 'Wedding Date', 'Venue Address', 'Photo Album', 'Contact Details'],
    liveDemoUrl: '/demo/eternal-moments',
  },
  {
    id: 'web-royal-union',
    name: 'Royal Union',
    slug: 'royal-union',
    category: 'Wedding',
    description: 'Traditional royal theme wedding invitation with countdown timer, family blessings, and sangeet / reception schedule.',
    shortDesc: 'Royal golden-accent wedding website for traditional Indian ceremonies.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Sangeet & Reception Schedule', 'Family Tree', 'Blessings Guestbook', 'Digital Map'],
    customization: ['Couple Names', 'Function Dates', 'Hotel Venue', 'RSVP WhatsApp'],
    liveDemoUrl: '/demo/royal-union',
  },
  {
    id: 'web-soulmates-forever',
    name: 'Soulmates Forever',
    slug: 'soulmates-forever',
    category: 'Wedding',
    description: 'Minimalist aesthetic wedding site with romantic background music player, photo wall, and dietary preference RSVP.',
    shortDesc: 'Modern aesthetic wedding site with photo gallery and online RSVP.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Photo Wall', 'Dietary Preference RSVP', 'Music Player', 'Live Stream Link'],
    customization: ['Names', 'Dates', 'Live Stream URL', 'Photos'],
    liveDemoUrl: '/demo/soulmates-forever',
  },

  // Birthday & Celebration
  {
    id: 'web-birthday-bash',
    name: 'Birthday Bash',
    slug: 'birthday-bash',
    category: 'Birthday',
    description: 'Vibrant and joyful birthday celebration website with live party countdown, wish board, venue map, and RSVP.',
    shortDesc: 'Joyful birthday party site with live countdown, wish wall, and party details.',
    featured: true,
    published: true,
    startingPrice: 149,
    features: ['Party Countdown', 'Guest Wish Wall', 'Location Map', 'Dress Code Details'],
    customization: ['Birthday Star Name', 'Age/Milestone', 'Party Venue', 'Date & Time'],
    liveDemoUrl: '/demo/birthday-bash',
  },
  {
    id: 'web-silver-jubilee',
    name: 'Silver Jubilee',
    slug: 'silver-jubilee',
    category: 'Celebration',
    description: 'Cherished 25th wedding anniversary celebration site highlighting life memories, travel stories, and dinner invite.',
    shortDesc: 'Anniversary celebration page honoring 25 years of togetherness.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Journey Timeline', 'Memory Slideshow', 'Dinner RSVP', 'Venue Guide'],
    customization: ['Couple Names', 'Years of Marriage', 'Venue', 'Photos'],
    liveDemoUrl: '/demo/silver-jubilee',
  },
  {
    id: 'web-baby-shower-miracle',
    name: 'Little Miracle Baby Shower',
    slug: 'baby-shower-miracle',
    category: 'Celebration',
    description: 'Cute pastel baby shower invite website featuring gift registry links, fun baby games schedule, and RSVP.',
    shortDesc: 'Pastel baby shower invitation site with gift registry and schedule.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Baby Shower Countdown', 'Gift Registry', 'Baby Games Schedule', 'RSVP'],
    customization: ['Parents Names', 'Baby Due Date', 'Event Venue', 'Gift Links'],
    liveDemoUrl: '/demo/baby-shower-miracle',
  },

  // Invitation
  {
    id: 'web-quickinvite-rsvp',
    name: 'QuickInvite RSVP',
    slug: 'quickinvite-rsvp',
    category: 'Invitation',
    description: 'Streamlined one-page digital event invitation with instant 1-click WhatsApp RSVP confirmation and calendar integration.',
    shortDesc: 'Instant digital invitation page with calendar add and WhatsApp RSVP.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['1-Click RSVP', 'Add to Google Calendar', 'Apple Maps / Google Maps', 'Host Contact'],
    customization: ['Event Title', 'Date & Time', 'Location', 'Host Mobile'],
    liveDemoUrl: '/demo/quickinvite-rsvp',
  },

  // College & Campus Events
  {
    id: 'web-college-fest-pro',
    name: 'College Fest Pro',
    slug: 'college-fest-pro',
    category: 'College',
    description: 'Comprehensive college festival website featuring dynamic event schedules, rulebooks, sponsor tiers, and registrations.',
    shortDesc: 'All-in-one college cultural & sports fest portal with online registration.',
    featured: true,
    published: true,
    startingPrice: 199,
    features: ['Inter-College Registration', 'Rulebooks PDF', 'Sponsor Tiers', 'Live Leaderboard'],
    customization: ['Fest Name', 'College Name', 'Event Schedule', 'Sponsor Logos'],
    liveDemoUrl: '/demo/college-fest-pro',
  },
  {
    id: 'web-hacksprint-techfest',
    name: 'HackSprint TechFest',
    slug: 'hacksprint-techfest',
    category: 'College',
    description: 'High-energy 24-hour hackathon portal with problem statements, mentor list, judging criteria, and submission links.',
    shortDesc: 'National level hackathon & technical symposium portal.',
    featured: false,
    published: true,
    startingPrice: 199,
    features: ['Team Registration', 'Tracks & Prizes', 'Mentor Profiles', 'Discord Community'],
    customization: ['Hackathon Name', 'Prize Pool', 'Tracks', 'Sponsors'],
    liveDemoUrl: '/demo/hacksprint-techfest',
  },
  {
    id: 'web-national-research-symposium',
    name: 'National Research Symposium',
    slug: 'national-research-symposium',
    category: 'College',
    description: 'Academic conference website with paper submission guidelines, keynote speaker lineup, and schedule agenda.',
    shortDesc: 'Scholarly seminar & research conference event portal.',
    featured: false,
    published: true,
    startingPrice: 199,
    features: ['Call for Papers', 'Speaker Lineup', 'Conference Schedule', 'Certificate Info'],
    customization: ['Department Name', 'Conference Theme', 'Important Dates', 'Contact Email'],
    liveDemoUrl: '/demo/national-research-symposium',
  },

  // Business & Local Services
  {
    id: 'web-gourmet-bistro-cafe',
    name: 'Gourmet Bistro & Cafe',
    slug: 'gourmet-bistro-cafe',
    category: 'Business',
    description: 'Delectable restaurant and café website featuring online visual food menu, chef specials, opening hours, and table reservations.',
    shortDesc: 'Stylish café & restaurant website with menu showcase and table reservation.',
    featured: true,
    published: true,
    startingPrice: 199,
    features: ['Digital Menu', 'Table Booking Form', 'Opening Hours', 'Google Reviews'],
    customization: ['Restaurant Name', 'Menu Items', 'Pricing', 'Phone / Zomato Links'],
    liveDemoUrl: '/demo/gourmet-bistro-cafe',
  },
  {
    id: 'web-luxe-salon-spa',
    name: 'Luxe Salon & Day Spa',
    slug: 'luxe-salon-spa',
    category: 'Business',
    description: 'Premium beauty parlour and wellness spa site featuring package pricing, expert stylists list, and appointment booking.',
    shortDesc: 'Luxury salon & wellness spa website with service menu and booking.',
    featured: false,
    published: true,
    startingPrice: 199,
    features: ['Service Price List', 'Stylist Profiles', 'Appointment Inquiry', 'Customer Testimonials'],
    customization: ['Salon Name', 'Services Offered', 'Price Sheet', 'WhatsApp Booking'],
    liveDemoUrl: '/demo/luxe-salon-spa',
  },
  {
    id: 'web-ironpulse-fitness-gym',
    name: 'IronPulse Fitness Gym',
    slug: 'ironpulse-fitness-gym',
    category: 'Business',
    description: 'Modern gym & CrossFit center website showcasing daily workout batches, membership pricing plans, and certified trainers.',
    shortDesc: 'Energetic gym website with batch schedules, trainer bios, and memberships.',
    featured: false,
    published: true,
    startingPrice: 199,
    features: ['Class Schedule', 'Membership Tiers', 'Trainer Bios', 'Free Trial Pass'],
    customization: ['Gym Name', 'Batch Timings', 'Membership Fees', 'Address'],
    liveDemoUrl: '/demo/ironpulse-fitness-gym',
  },
  {
    id: 'web-prime-estates-realty',
    name: 'PrimeEstates Realty',
    slug: 'prime-estates-realty',
    category: 'Business',
    description: 'High-converting real estate broker and project showcase website with property listings, specifications, and site tour booking.',
    shortDesc: 'Real estate property rental & sales showcase website with inquiry lead form.',
    featured: false,
    published: true,
    startingPrice: 249,
    features: ['Property Cards', 'Floor Plans', 'Amenities Grid', 'Schedule Site Visit'],
    customization: ['Builder/Agent Name', 'Property List', 'Price Ranges', 'Brochure PDF'],
    liveDemoUrl: '/demo/prime-estates-realty',
  },
  {
    id: 'web-apex-buildcon',
    name: 'Apex Buildcon & Architecture',
    slug: 'apex-buildcon',
    category: 'Business',
    description: 'Heavy construction and interior design firm profile showcasing portfolio projects, turnkey services, and quotation requests.',
    shortDesc: 'Construction firm & civil contractor website with project portfolio.',
    featured: false,
    published: true,
    startingPrice: 249,
    features: ['Completed Projects Grid', 'Service Offerings', 'Client Logos', 'Request a Quote'],
    customization: ['Company Name', 'Projects Gallery', 'Client List', 'Phone & Email'],
    liveDemoUrl: '/demo/apex-buildcon',
  },
  {
    id: 'web-nexus-corporate-consult',
    name: 'Nexus Corporate Consult',
    slug: 'nexus-corporate-consult',
    category: 'Business',
    description: 'Trustworthy corporate consultancy profile site with company vision, leadership team bios, client case studies, and contact.',
    shortDesc: 'Corporate consulting & advisory firm website with services and team bios.',
    featured: false,
    published: true,
    startingPrice: 249,
    features: ['Leadership Bios', 'Corporate Solutions', 'Client Case Studies', 'Inquiry Form'],
    customization: ['Firm Name', 'Services', 'Partner Profiles', 'Office Location'],
    liveDemoUrl: '/demo/nexus-corporate-consult',
  },
  {
    id: 'web-brightminds-academy',
    name: 'BrightMinds Academy',
    slug: 'brightminds-academy',
    category: 'Business',
    description: 'Coaching institute portal with entrance exam course details, batch schedules, faculty achievements, and admission inquiry.',
    shortDesc: 'Coaching classes website with batch timings, fee details, and demo seat booking.',
    featured: false,
    published: true,
    startingPrice: 199,
    features: ['Course Catalog', 'Topper Hall of Fame', 'Batch Schedules', 'Demo Class Registration'],
    customization: ['Institute Name', 'Exams Covered', 'Faculty List', 'Phone & Address'],
    liveDemoUrl: '/demo/brightminds-academy',
  },

  // Portfolios
  {
    id: 'web-shuttercraft-studio',
    name: 'ShutterCraft Studio',
    slug: 'shuttercraft-studio',
    category: 'Portfolio',
    description: 'Clean, full-bleed photography portfolio featuring wedding, portrait, and commercial shoots with package booking inquiry.',
    shortDesc: 'Visual photo gallery portfolio for professional photographers.',
    featured: true,
    published: true,
    startingPrice: 179,
    features: ['Full-Width Gallery', 'Shoot Packages', 'Gear Specs', 'Direct Booking Inquiry'],
    customization: ['Photographer Name', 'Portfolio Albums', 'Shoot Rates', 'Instagram Feed'],
    liveDemoUrl: '/demo/shuttercraft-studio',
  },
  {
    id: 'web-devcraft-freelance',
    name: 'DevCraft Freelance Studio',
    slug: 'devcraft-freelance',
    category: 'Portfolio',
    description: 'Modern developer portfolio with live project case studies, client reviews, tech stack tags, and freelance availability badge.',
    shortDesc: 'High-impact freelance portfolio with project case studies and skills.',
    featured: false,
    published: true,
    startingPrice: 179,
    features: ['Case Studies', 'Tech Stack Icons', 'Client Recommendations', 'Contact Form'],
    customization: ['Developer Name', 'Github / LinkedIn', 'Projects', 'Hourly / Project Rate'],
    liveDemoUrl: '/demo/devcraft-freelance',
  },
  {
    id: 'web-portfolio-plus',
    name: 'Portfolio Plus',
    slug: 'portfolio-plus',
    category: 'Portfolio',
    description: 'Beautiful portfolio website with project gallery, about section, skills display, and contact form. Ideal for designers, developers, and creatives.',
    shortDesc: 'Beautiful portfolio website with project gallery and skills display.',
    featured: false,
    published: true,
    startingPrice: 179,
    features: ['Project Gallery', 'About Section', 'Skills Display', 'Contact Form', 'Social Links', 'Resume Download'],
    customization: ['Name', 'Bio', 'Projects', 'Skills', 'Contact Details', 'Social Links', 'Resume'],
    liveDemoUrl: '/demo/portfolio-plus',
  },

  // Startup & Launch
  {
    id: 'web-startup-launchpad',
    name: 'Startup Launchpad',
    slug: 'startup-launchpad',
    category: 'Startup',
    description: 'High-converting SaaS landing page with product mockups, benefit breakdown, customer proof, and early-access CTA.',
    shortDesc: 'SaaS & startup landing page with product mockups and lead capture.',
    featured: true,
    published: true,
    startingPrice: 299,
    features: ['Feature Hero', 'Product Walkthrough', 'Pricing Grid', 'Early Access Waitlist'],
    customization: ['Product Name', 'Pitch Slogan', 'Features List', 'Waitlist Email'],
    liveDemoUrl: '/demo/startup-launchpad',
  },
  {
    id: 'web-nextgen-gadget-launch',
    name: 'NextGen Gadget Launch',
    slug: 'nextgen-gadget-launch',
    category: 'Product Launch',
    description: 'Cinematic single-product landing page designed for hardware, fashion, or book releases with preorder button.',
    shortDesc: 'Product announcement page with countdown timer and preorder checkout.',
    featured: false,
    published: true,
    startingPrice: 299,
    features: ['360 Product Showcase', 'Technical Specs', 'Launch Countdown', 'Pre-Order CTA'],
    customization: ['Product Title', 'Launch Date', 'Specs Sheet', 'Order Link'],
    liveDemoUrl: '/demo/nextgen-gadget-launch',
  },

  // Events & Project
  {
    id: 'web-summit-global-conference',
    name: 'Summit Global Conference',
    slug: 'summit-global-conference',
    category: 'Events',
    description: 'International conference and expo website with multi-track agendas, speaker highlights, ticketing tiers, and venue guide.',
    shortDesc: 'Conference & summit portal with speaker lineup and ticket passes.',
    featured: true,
    published: true,
    startingPrice: 249,
    features: ['Multi-Track Agenda', 'Keynote Speakers', 'Pass Tiers', 'Sponsors Carousel'],
    customization: ['Conference Title', 'Dates', 'Speakers List', 'Venue'],
    liveDemoUrl: '/demo/summit-global-conference',
  },
  {
    id: 'web-event-hub',
    name: 'Event Hub',
    slug: 'event-hub',
    category: 'Events',
    description: 'Versatile event website for conferences, seminars, workshops, and meetups. Includes schedule, speaker profiles, registration, and venue information.',
    shortDesc: 'Versatile event website with schedule and speaker profiles.',
    featured: false,
    published: true,
    startingPrice: 249,
    features: ['Schedule', 'Speaker Profiles', 'Registration', 'Venue Info', 'Sponsors', 'Contact'],
    customization: ['Event Name', 'Dates', 'Speakers', 'Schedule', 'Venue', 'Registration Form', 'Sponsors'],
    liveDemoUrl: '/demo/event-hub',
  },
  {
    id: 'web-project-capstone-demo',
    name: 'Project Capstone Demo',
    slug: 'project-capstone-demo',
    category: 'Project',
    description: 'Dedicated final-year or client project website with live interactive demo preview, architecture diagram, and Github repository link.',
    shortDesc: 'Project portfolio site highlighting system architecture, live demo, and tech docs.',
    featured: false,
    published: true,
    startingPrice: 179,
    features: ['System Architecture', 'Live Embedded Demo', 'Tech Stack Badges', 'Documentation PDF'],
    customization: ['Project Title', 'Authors', 'Github URL', 'Demo Link'],
    liveDemoUrl: '/demo/project-capstone-demo',
  },

  // Personal & Celebration
  {
    id: 'web-creative-identity',
    name: 'Creative Identity',
    slug: 'creative-identity',
    category: 'Personal',
    description: 'Modern digital bio link and resume website for creators, consultants, and public figures with links and newsletter sign-up.',
    shortDesc: 'Personal branding & bio-link page with career timeline and social channels.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Hero Avatar', 'Social Link Tree', 'Resume Timeline', 'Newsletter Box'],
    customization: ['Your Name', 'Bio Blurb', 'Social Handles', 'Contact'],
    liveDemoUrl: '/demo/creative-identity',
  },
  {
    id: 'web-grand-celebration-gala',
    name: 'Grand Celebration Gala',
    slug: 'grand-celebration-gala',
    category: 'Celebration',
    description: 'Festive event landing page for community festivals, cultural galas, and religious get-togethers with passes and timings.',
    shortDesc: 'Gala & community celebration website with program schedule and venue access.',
    featured: false,
    published: true,
    startingPrice: 149,
    features: ['Gala Schedule', 'Chief Guests', 'Pass Registration', 'Location Map'],
    customization: ['Gala Name', 'Event Date', 'Venue', 'Special Guests'],
    liveDemoUrl: '/demo/grand-celebration-gala',
  },
]
