import { DestinationData } from './types';

export const DESTINATIONS: DestinationData[] = [
  {
    id: 'japan',
    name: 'Japan',
    country: 'Japan',
    tagline: 'A tapestry of ancient ritual and hyper-modern wonder',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=2000&q=85',
    region: 'East Asia',
    defaultDays: 7,
    bestSeason: 'Spring (Cherry Blossoms) & Autumn (Crimson Foliage)',
    vibe: ['Culture', 'Food', 'Photography', 'Futuristic', 'Nature'],
    description:
      'From the electric neon corridors of Shinjuku to the moss-carpeted zen gardens of Kyoto, Japan is an intoxicating immersion into deliberate craftsmanship, transcendent culinary mastery, and quiet reverence.',
    sampleBudget: { low: 1800, moderate: 3200, luxury: 6800 },
    stops: [
      {
        id: 'tokyo',
        name: 'Tokyo',
        subtitle: 'A City That Never Stops',
        image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1600&q=80',
        coordinates: { x: 74, y: 48 },
        description: 'Dizzying skyscraper canyons, quiet ramen alleys, and 300-year-old shrines tucked between cyber malls.',
        dayNumbers: [1, 2],
      },
      {
        id: 'mt-fuji',
        name: 'Mount Fuji & Hakone',
        subtitle: 'Sacred Silhouette & Mist',
        image: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=1600&q=80',
        coordinates: { x: 62, y: 55 },
        description: 'Volcanic hot springs (onsen), lakeside cedar forests, and the snow-dusted volcano rising above cedar groves.',
        dayNumbers: [3],
      },
      {
        id: 'kyoto',
        name: 'Kyoto',
        subtitle: 'Time Moves Differently Here',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=80',
        coordinates: { x: 42, y: 64 },
        description: 'Ten thousand vermilion torii gates at Fushimi Inari, serene rock gardens, and traditional geisha tea houses.',
        dayNumbers: [4, 5],
      },
      {
        id: 'osaka',
        name: 'Osaka',
        subtitle: 'Eat. Explore. Repeat.',
        image: 'https://images.unsplash.com/photo-1590559899731-a372a1464309?auto=format&fit=crop&w=1600&q=80',
        coordinates: { x: 34, y: 68 },
        description: 'The rebellious culinary soul of western Japan. Dotonbori canals glowing with retro signs and sizzling grills.',
        dayNumbers: [6, 7],
      },
    ],
    sampleItinerary: [
      {
        dayNumber: 1,
        title: 'Arrival into the Neon Grid',
        locationName: 'Tokyo (Shinjuku & Shibuya)',
        locationId: 'tokyo',
        bgImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2000&q=80',
        theme: 'Urban Energy & Arrival',
        tips: 'Get an IC card (Suica/Pasmo) for seamless train tap-ins across the capital.',
        activities: [
          { id: 'act-1-1', time: '14:00', title: 'Hotel Check-in & Panoramic Shinjuku View', category: 'relaxation', duration: '2 hrs', location: 'Park Hyatt / Shinjuku', cost: 0, included: true },
          { id: 'act-1-2', time: '17:30', title: 'Sunset at Shibuya Crossing & Sky Deck', category: 'sightseeing', duration: '2 hrs', location: 'Shibuya Scramble', cost: 25, included: true },
          { id: 'act-1-3', time: '20:00', title: 'Hidden Alleyway Yakitori Crawl at Omoide Yokocho', category: 'food', duration: '2.5 hrs', location: 'Shinjuku Memory Lane', cost: 45, included: true },
        ],
      },
      {
        dayNumber: 2,
        title: 'Ancient Roots & Modern Craft',
        locationName: 'Tokyo (Asakusa & Ginza)',
        locationId: 'tokyo',
        bgImage: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=2000&q=80',
        theme: 'Ritual & Precision',
        tips: 'Visit Senso-ji early before 9:00 AM to enjoy the incense cloud in stillness.',
        activities: [
          { id: 'act-2-1', time: '08:30', title: 'Morning Incense Purification at Senso-ji Temple', category: 'culture', duration: '2 hrs', location: 'Asakusa', cost: 0, included: true },
          { id: 'act-2-2', time: '12:00', title: 'Artisanal Soba Tasting in Yanaka Old Town', category: 'food', duration: '1.5 hrs', location: 'Yanaka Ginza', cost: 30, included: true },
          { id: 'act-2-3', time: '15:00', title: 'Ginza Six Architecture & Modern Japanese Stationery', category: 'sightseeing', duration: '2.5 hrs', location: 'Ginza', cost: 20, included: true },
          { id: 'act-2-4', time: '19:30', title: 'Omakase Sushi Counter Experience with Master Chef', category: 'food', duration: '2 hrs', location: 'Tsukiji Outer Market', cost: 140, included: true },
        ],
      },
      {
        dayNumber: 3,
        title: 'The Sacred Mountain & Mineral Waters',
        locationName: 'Hakone & Lake Ashi',
        locationId: 'mt-fuji',
        bgImage: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=2000&q=80',
        theme: 'Alpine Serenity & Onsen',
        tips: 'Pack a small overnight bag; forward large luggage straight to Kyoto.',
        activities: [
          { id: 'act-3-1', time: '09:00', title: 'Romancecar Train through Misty Cedar Mountains', category: 'adventure', duration: '1.5 hrs', location: 'Odakyu Line', cost: 25, included: true },
          { id: 'act-3-2', time: '12:30', title: 'Hakone Ropeway & Sulfur Vents of Owakudani', category: 'sightseeing', duration: '2 hrs', location: 'Mount Hakone', cost: 35, included: true },
          { id: 'act-3-3', time: '16:00', title: 'Open-Air Rotenburo Onsen Bath at Traditional Ryokan', category: 'relaxation', duration: '3 hrs', location: 'Hakone Ginyu', cost: 80, included: true },
          { id: 'act-3-4', time: '19:30', title: 'Nine-Course Seasonal Kaiseki Dinner', category: 'food', duration: '2 hrs', location: 'Private Ryokan Tatami Room', cost: 110, included: true },
        ],
      },
      {
        dayNumber: 4,
        title: 'Bullet Train to the Imperial Sanctuary',
        locationName: 'Kyoto (Higashiyama)',
        locationId: 'kyoto',
        bgImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=2000&q=80',
        theme: 'Whispering Bamboo & Heritage',
        tips: 'The Shinkansen hits 285 km/h; grab an Ekiben bento box at the platform.',
        activities: [
          { id: 'act-4-1', time: '10:00', title: 'Tokaido Shinkansen Bullet Train Voyage', category: 'adventure', duration: '2 hrs', location: 'Tokyo to Kyoto', cost: 95, included: true },
          { id: 'act-4-2', time: '14:00', title: 'Walking the Thousand Vermilion Gates of Fushimi Inari', category: 'culture', duration: '3 hrs', location: 'Southern Kyoto', cost: 0, included: true },
          { id: 'act-4-3', time: '18:30', title: 'Twilight Lantern Stroll in Gion Geisha District', category: 'culture', duration: '2 hrs', location: 'Gion Hanamikoji', cost: 0, included: true },
        ],
      },
      {
        dayNumber: 5,
        title: 'Zen Gardens & Ceramic Paths',
        locationName: 'Kyoto (Arashiyama & Kinkaku-ji)',
        locationId: 'kyoto',
        bgImage: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=2000&q=80',
        theme: 'Stillness & Craft',
        tips: 'Listen to the wind rustling through the bamboo forest at first light.',
        activities: [
          { id: 'act-5-1', time: '07:30', title: 'Solitary Walk through Sagano Bamboo Forest', category: 'nature', duration: '1.5 hrs', location: 'Arashiyama', cost: 0, included: true },
          { id: 'act-5-2', time: '10:30', title: 'Private Tea Ceremony (Chado) with a 15th-Gen Master', category: 'culture', duration: '2 hrs', location: 'Daitoku-ji Subtemple', cost: 75, included: true },
          { id: 'act-5-3', time: '14:30', title: 'Gold Leaf Reflection at Kinkaku-ji', category: 'sightseeing', duration: '1.5 hrs', location: 'Northern Kyoto', cost: 15, included: true },
          { id: 'act-5-4', time: '19:00', title: 'Tofu Kaiseki on River Deck Platforms (Kawayuka)', category: 'food', duration: '2 hrs', location: 'Kamogawa River', cost: 85, included: true },
        ],
      },
      {
        dayNumber: 6,
        title: 'The Kitchen of the Nation',
        locationName: 'Osaka (Namba & Dotonbori)',
        locationId: 'osaka',
        bgImage: 'https://images.unsplash.com/photo-1590559899731-a372a1464309?auto=format&fit=crop&w=2000&q=80',
        theme: 'Street Food Extravaganza',
        tips: 'Kuidaore is the Osaka philosophy: "eat until you drop".',
        activities: [
          { id: 'act-6-1', time: '10:30', title: 'Scenic Express to Osaka & Castle Ramparts', category: 'sightseeing', duration: '2.5 hrs', location: 'Osaka Castle Grounds', cost: 20, included: true },
          { id: 'act-6-2', time: '14:00', title: 'Retro Shinsekai District & Kushikatsu Skewers', category: 'food', duration: '2.5 hrs', location: 'Shinsekai', cost: 35, included: true },
          { id: 'act-6-3', time: '18:30', title: 'Neon Dotonbori Canal Walk & Takoyaki Feast', category: 'food', duration: '3 hrs', location: 'Dotonbori', cost: 50, included: true },
        ],
      },
      {
        dayNumber: 7,
        title: 'Farewell to the Rising Sun',
        locationName: 'Osaka / Kansai Departure',
        locationId: 'osaka',
        bgImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2000&q=80',
        theme: 'Memories & Departure',
        tips: 'Buy matcha treats and knife souvenirs at the departure hall.',
        activities: [
          { id: 'act-7-1', time: '09:00', title: 'Last Coffee & Souvenir Hunting in Umeda', category: 'relaxation', duration: '2.5 hrs', location: 'Grand Front Osaka', cost: 40, included: true },
          { id: 'act-7-2', time: '12:30', title: 'Haruka Airport Express to Kansai International', category: 'sightseeing', duration: '1 hr', location: 'KIX Airport', cost: 25, included: true },
        ],
      },
    ],
    stays: [
      {
        id: 'stay-1',
        name: 'Hoshinoya Kyoto',
        location: 'Arashiyama, Kyoto',
        style: 'Riverside Luxury Ryokan',
        pricePerNight: 580,
        rating: 4.95,
        image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1200&q=80',
        nights: 2,
        selected: true,
      },
      {
        id: 'stay-2',
        name: 'Aman Tokyo',
        location: 'Otemachi, Tokyo',
        style: 'Modern Minimalist Sanctuary',
        pricePerNight: 720,
        rating: 4.98,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
        nights: 2,
        selected: true,
      },
      {
        id: 'stay-3',
        name: 'Gora Kadan Hakone',
        location: 'Hakone Onsen Valley',
        style: 'Imperial Villa Thermal Ryokan',
        pricePerNight: 640,
        rating: 4.92,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        nights: 1,
        selected: true,
      },
      {
        id: 'stay-4',
        name: 'W Osaka Design Hotel',
        location: 'Shinsaibashi, Osaka',
        style: 'Vibrant Cosmopolitan Suite',
        pricePerNight: 390,
        rating: 4.88,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
        nights: 2,
        selected: true,
      },
    ],
    foods: [
      { id: 'food-1', name: 'Tonkotsu Ramen with Chashu', origin: 'Tokyo / Hakata', description: 'Rich 18-hour pork bone broth with springy handmade noodles and cured egg.', priceEstimate: 16, image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80', selected: true },
      { id: 'food-2', name: 'Edomae Nigiri Omakase', origin: 'Tokyo Bay', description: 'Freshly aged bluefin otoro, sea urchin, and vinegared warm rice seasoned with shoyu.', priceEstimate: 120, image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80', selected: true },
      { id: 'food-3', name: 'Crispy Dotonbori Takoyaki', origin: 'Osaka', description: 'Sizzling spherical octopus dumplings brushed with sweet brown sauce and bonito flakes.', priceEstimate: 8, image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80', selected: true },
      { id: 'food-4', name: 'Kyoto Ceremonial Uji Matcha Parfait', origin: 'Kyoto', description: 'Deep bittersweet stone-ground matcha cake with dango and sweet red bean paste.', priceEstimate: 12, image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'exp-1', title: 'Early Morning Private Tea Ceremony', location: 'Kyoto Daitoku-ji', price: 95, duration: '2 hrs', image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80', highlight: 'Ancient meditative ritual in 400-year-old tatami room', selected: true },
      { id: 'exp-2', title: 'Mount Fuji Panoramic Helicopter Flight', location: 'Lake Kawaguchi', price: 280, duration: '45 mins', image: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=800&q=80', highlight: 'Hovering over the snow crater at sunrise', selected: true },
      { id: 'exp-3', title: 'Tokyo Cyberpunk Cyber-Photography Tour', location: 'Shinjuku & Akihabara', price: 75, duration: '3 hrs', image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80', highlight: 'Pro camera techniques in rainy neon alleys', selected: true },
      { id: 'exp-4', title: 'Osaka Hidden Alley Food & Sake Crawl', location: 'Dotonbori & Shinsekai', price: 65, duration: '3.5 hrs', image: 'https://images.unsplash.com/photo-1590559899731-a372a1464309?auto=format&fit=crop&w=800&q=80', highlight: 'Six authentic street stalls unknown to tourists', selected: true },
    ],
    transports: [
      { from: 'Tokyo', to: 'Hakone', mode: 'Odakyu Romancecar', duration: '1h 25m', cost: 24 },
      { from: 'Hakone', to: 'Kyoto', mode: 'Tokaido Shinkansen Bullet Train', duration: '2h 10m', cost: 110 },
      { from: 'Kyoto', to: 'Osaka', mode: 'Hankyu Kyoto Special Rapid', duration: '32m', cost: 12 },
    ],
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    country: 'Switzerland',
    tagline: 'Glacier peaks, emerald lakes, and panoramic alpine trains',
    heroImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=2000&q=85',
    region: 'Western Europe',
    defaultDays: 6,
    bestSeason: 'June to September (Hiking) or Dec to March (Skiing)',
    vibe: ['Nature', 'Luxury', 'Adventure', 'Photography'],
    description: 'Crisp mountain air, cowbells chiming across flower-filled meadows, and cogwheel trains ascending into the clouds toward the Matterhorn.',
    sampleBudget: { low: 2200, moderate: 4200, luxury: 8500 },
    stops: [
      { id: 'zurich', name: 'Zurich & Lucerne', subtitle: 'Lakeside Elegance', image: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 45, y: 35 }, description: 'Cobbled guild houses, wooden Chapel Bridge, and paddle steamers on glassy water.', dayNumbers: [1, 2] },
      { id: 'interlaken', name: 'Interlaken & Lauterbrunnen', subtitle: 'Valley of 72 Waterfalls', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 50, y: 55 }, description: 'Sheer limestone cliffs plunging into emerald valleys dotted with timber chalets.', dayNumbers: [3, 4] },
      { id: 'zermatt', name: 'Zermatt & Matterhorn', subtitle: 'The Crown of the Alps', image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 55, y: 75 }, description: 'Car-free mountain village under the razor silhouette of the world’s most iconic peak.', dayNumbers: [5, 6] },
    ],
    sampleItinerary: [
      { dayNumber: 1, title: 'Arrival along the Limmat River', locationName: 'Zurich Old Town', locationId: 'zurich', bgImage: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=2000&q=80', theme: 'Historic Arrival', tips: 'Get the Swiss Travel Pass for unlimited trains, boats, and mountain lifts.', activities: [] },
      { dayNumber: 2, title: 'Paddle Steamers and Mount Pilatus', locationName: 'Lucerne', locationId: 'zurich', bgImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2000&q=80', theme: 'Lakes & Peaks', tips: 'Ride the world steepest cogwheel railway.', activities: [] },
    ],
    stays: [
      { id: 'sw-stay-1', name: 'The Chedi Andermatt', location: 'Andermatt', style: 'Alpine Zen Luxury', pricePerNight: 750, rating: 4.96, image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
      { id: 'sw-stay-2', name: 'Mont Cervin Palace', location: 'Zermatt', style: 'Historic Grand Chalet', pricePerNight: 620, rating: 4.91, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
    ],
    foods: [
      { id: 'sw-food-1', name: 'Alpine Gruyère Cheese Fondue', origin: 'Fribourg', description: 'Melted aged raw milk cheese with white wine, garlic, and crusty sourdough cubes.', priceEstimate: 35, image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80', selected: true },
      { id: 'sw-food-2', name: 'Crispy Swiss Rösti with Smoked Bratwurst', origin: 'Bern', description: 'Grated butter-crisped potato cake with alpine butter and rosemary.', priceEstimate: 28, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'sw-exp-1', title: 'Glacier Express Scenic Train Journey', location: 'St. Moritz to Zermatt', price: 185, duration: '7.5 hrs', image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80', highlight: 'Panoramic glass dome ceiling over 291 mountain bridges', selected: true },
    ],
    transports: [
      { from: 'Zurich', to: 'Interlaken', mode: 'Swiss Federal Railway', duration: '1h 55m', cost: 65 },
      { from: 'Interlaken', to: 'Zermatt', mode: 'Matterhorn Gotthard Bahn', duration: '2h 10m', cost: 85 },
    ],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    tagline: 'Island of the Gods: emerald terraces, surf breaks, and spiritual healing',
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2000&q=85',
    region: 'Southeast Asia',
    defaultDays: 6,
    bestSeason: 'April to October (Dry Season)',
    vibe: ['Relaxation', 'Nature', 'Adventure', 'Food', 'Culture'],
    description: 'Frangipani incense floating over stone temples, jungle infinity pools, wild volcanic hikes at dawn, and world-class ocean swell.',
    sampleBudget: { low: 1100, moderate: 2100, luxury: 4500 },
    stops: [
      { id: 'ubud', name: 'Ubud', subtitle: 'Spiritual Jungle Heart', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 50, y: 40 }, description: 'Tegallalang rice terraces, sacred monkey forests, yoga shalas, and herbal organic dining.', dayNumbers: [1, 2, 3] },
      { id: 'uluwatu', name: 'Uluwatu & Seminyak', subtitle: 'Cliffside Ocean Chants', image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 45, y: 80 }, description: 'Dramatic cliff temples where Kecak fire dancers chant against the fiery Indian Ocean sunset.', dayNumbers: [4, 5, 6] },
    ],
    sampleItinerary: [
      { dayNumber: 1, title: 'Into the Forest of Frangipani', locationName: 'Ubud Valley', locationId: 'ubud', bgImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2000&q=80', theme: 'Arrival & Jungle Spa', tips: 'Wake up for early morning temple walks before tour coaches arrive.', activities: [] },
    ],
    stays: [
      { id: 'bali-stay-1', name: 'Four Seasons Resort Sayan', location: 'Ubud River Valley', style: 'Suspended Lotus Villa', pricePerNight: 550, rating: 4.97, image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
    ],
    foods: [
      { id: 'bali-food-1', name: 'Babi Guling Spiced Roast', origin: 'Gianyar', description: 'Crispy roasted pig rubbed in turmeric, lemongrass, shallots, and ginger.', priceEstimate: 10, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'bali-exp-1', title: 'Mount Batur Sunrise Caldera Trek', location: 'Kintamani', price: 55, duration: '5 hrs', image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80', highlight: 'Breakfast cooked over volcanic steam at 1,717m altitude', selected: true },
    ],
    transports: [
      { from: 'Denpasar', to: 'Ubud', mode: 'Private Chauffeured SUV', duration: '1h 15m', cost: 35 },
    ],
  },
  {
    id: 'italy',
    name: 'Italy',
    country: 'Italy',
    tagline: 'Renaissance grandeur, sun-drenched vineyards, and dolce vita',
    heroImage: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=2000&q=85',
    region: 'Southern Europe',
    defaultDays: 8,
    bestSeason: 'May to June & September to October',
    vibe: ['Culture', 'Food', 'Romance', 'Photography', 'Architecture'],
    description: 'Marble fountains echoing in Rome, golden light over Tuscan rolling hills, and handmade pasta prepared with heirloom tomatoes and sea salt.',
    sampleBudget: { low: 1900, moderate: 3600, luxury: 7500 },
    stops: [
      { id: 'rome', name: 'Rome', subtitle: 'The Eternal City', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 48, y: 60 }, description: 'Colosseum ruins, Vatican corridors, and evening strolls by the Trevi Fountain.', dayNumbers: [1, 2, 3] },
      { id: 'florence', name: 'Florence & Tuscany', subtitle: 'Cradle of the Renaissance', image: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 42, y: 40 }, description: 'Brunelleschi’s dome, Chianti vineyards, and truffle tagliatelle.', dayNumbers: [4, 5, 6] },
      { id: 'amalfi', name: 'Amalfi Coast', subtitle: 'Cliffs of Lemon & Azure', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 60, y: 78 }, description: 'Pastel villages cascading down cliffs into the sapphire Tyrrhenian Sea.', dayNumbers: [7, 8] },
    ],
    sampleItinerary: [
      { dayNumber: 1, title: 'Among the Imperial Marble', locationName: 'Rome (Historic Center)', locationId: 'rome', bgImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=2000&q=80', theme: 'Antiquity & Wine', tips: 'Pre-book Colosseum tickets 30 days in advance.', activities: [] },
    ],
    stays: [
      { id: 'it-stay-1', name: 'Belmond Hotel Caruso', location: 'Ravello, Amalfi', style: '11th-Century Clifftop Palace', pricePerNight: 890, rating: 4.99, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
    ],
    foods: [
      { id: 'it-food-1', name: 'Authentic Roman Cacio e Pepe', origin: 'Rome', description: 'Fresh tonnarelli pasta tossed with aged Pecorino Romano and crushed toasted black peppercorns.', priceEstimate: 18, image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'it-exp-1', title: 'Vintage Alfa Romeo Drive through Chianti', location: 'Tuscany', price: 210, duration: '4 hrs', image: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=800&q=80', highlight: 'Driving top-down past cypress lines and stone wineries', selected: true },
    ],
    transports: [
      { from: 'Rome', to: 'Florence', mode: 'Frecciarossa High Speed Train', duration: '1h 36m', cost: 55 },
    ],
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    country: 'New Zealand',
    tagline: 'Pristine fjords, geothermal geysers, and cinematic wilderness',
    heroImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=2000&q=85',
    region: 'Oceania',
    defaultDays: 9,
    bestSeason: 'December to March (Southern Hemisphere Summer)',
    vibe: ['Adventure', 'Nature', 'Road Trip', 'Photography'],
    description: 'Snow-capped Southern Alps reflected in mirror lakes, roaring waterfalls in Milford Sound, and pure untamed Pacific solitude.',
    sampleBudget: { low: 2400, moderate: 4500, luxury: 8900 },
    stops: [
      { id: 'auckland', name: 'Auckland & Rotorua', subtitle: 'Volcanic Springs', image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 70, y: 30 }, description: 'Geothermal geysers, Maori cultural marae, and black sand surf beaches.', dayNumbers: [1, 2, 3] },
      { id: 'queenstown', name: 'Queenstown & Wanaka', subtitle: 'Adventure Capital of the World', image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 30, y: 70 }, description: 'Lake Wakatipu ringed by The Remarkables, alpine vineyards, and jet boats.', dayNumbers: [4, 5, 6] },
      { id: 'milford', name: 'Milford Sound', subtitle: 'The Eighth Wonder', image: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 20, y: 80 }, description: 'Towering rainforest cliffs rising sheer out of dark glacier waters.', dayNumbers: [7, 8, 9] },
    ],
    sampleItinerary: [
      { dayNumber: 1, title: 'Arrival into the City of Sails', locationName: 'Auckland Harbour', locationId: 'auckland', bgImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=2000&q=80', theme: 'Maritime Arrival', tips: 'Pick up your rental 4WD directly at the terminal.', activities: [] },
    ],
    stays: [
      { id: 'nz-stay-1', name: 'Matakauri Lodge', location: 'Queenstown', style: 'Lakefront Alpine Sanctuary', pricePerNight: 950, rating: 4.98, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
    ],
    foods: [
      { id: 'nz-food-1', name: 'Canterbury Roast Lamb & Mint Jelly', origin: 'South Island', description: 'Pasture-raised lamb slow roasted with rosemary, kumara potatoes, and pinot jus.', priceEstimate: 38, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'nz-exp-1', title: 'Milford Sound Cruise Under Stirling Falls', location: 'Fiordland', price: 120, duration: '3 hrs', image: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=800&q=80', highlight: 'Feeling the glacier spray beneath 150-meter waterfalls', selected: true },
    ],
    transports: [
      { from: 'Auckland', to: 'Queenstown', mode: 'Scenic Domestic Flight', duration: '1h 50m', cost: 140 },
    ],
  },
  {
    id: 'paris',
    name: 'France (Paris & Provence)',
    country: 'France',
    tagline: 'Haute couture, candlelit bistros, and lavender hilltops',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=2000&q=85',
    region: 'Western Europe',
    defaultDays: 6,
    bestSeason: 'April to October',
    vibe: ['Culture', 'Food', 'Romance', 'Architecture', 'Luxury'],
    description: 'The golden hour over the Seine, crusty baguettes from neighborhood boulangeries, and timeless Impressionist masterpieces.',
    sampleBudget: { low: 2000, moderate: 3800, luxury: 7800 },
    stops: [
      { id: 'paris-city', name: 'Paris', subtitle: 'The City of Light', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 50, y: 35 }, description: 'Eiffel Tower sparkle, Marais vintage boutiques, and cafe terraces.', dayNumbers: [1, 2, 3, 4] },
      { id: 'provence', name: 'Provence & Côte d’Azur', subtitle: 'Sun-Drenched South', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80', coordinates: { x: 60, y: 80 }, description: 'Lavender fields, ancient olive mills, and Mediterranean coastal paths.', dayNumbers: [5, 6] },
    ],
    sampleItinerary: [
      { dayNumber: 1, title: 'First Stroll along the Seine', locationName: 'Saint-Germain-des-Prés', locationId: 'paris-city', bgImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=2000&q=80', theme: 'Bohemian Elegance', tips: 'Order un café serré standing at the zinc bar.', activities: [] },
    ],
    stays: [
      { id: 'fr-stay-1', name: 'Hôtel Plaza Athénée', location: 'Avenue Montaigne, Paris', style: 'Haute Parisian Palace', pricePerNight: 1100, rating: 4.97, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', nights: 3, selected: true },
    ],
    foods: [
      { id: 'fr-food-1', name: 'Duck Confit with Sarladaise Potatoes', origin: 'Paris / Gascony', description: 'Crispy slow-cooked duck leg with garlic parsley fingerling potatoes.', priceEstimate: 32, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', selected: true },
    ],
    experiences: [
      { id: 'fr-exp-1', title: 'After-Hours Louvre Curated Private Tour', location: 'Paris', price: 290, duration: '2.5 hrs', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80', highlight: 'Standing alone before the Mona Lisa and Winged Victory', selected: true },
    ],
    transports: [
      { from: 'Paris', to: 'Avignon (Provence)', mode: 'TGV InOui High Speed', duration: '2h 40m', cost: 85 },
    ],
  },
];
